export const serviceCardIds = [
  "vitakid",
  "familyPlanning",
  "safeMotherhood",
  "reproductiveInfections",
  "dysmenorrhea",
  "pelvicInflammation",
  "reproductiveCancerPrevention",
  "pregnancyTest",
  "educationRooms",
  "care1000Days",
  "homeVisits",
  "breastExam",
  "ultrasound",
  "gynecologyExam",
  "smearCollection",
  "ambulatoryVisits",
  "colposcopy",
  "earlyCare",
  "childEducation",
  "educationSixMonthsToSixYears",
  "educationTwoToSevenYears",
];

